camaraproject/DeviceLocation

code/API_definitions/location.yaml

As introduced in #26, I have prepared a model to evolve the Area concept:
- Initially only the current Circle is considered
- Intention of this PR is to agree on the polymorphic structure to support more types of Area in the near future (Polygon, Postcode...)
Preview of current proposal with Redoc
Use of `oneOf` and `allOf` and how they can be combined is a bit confusing in the spec. I opted to create an `Area` object which must be `oneOf` the sub-types, and create a `BaseArea` object to hold the common properties, which is only the `type`.
With Swagger 2.0, where `oneOf` was not available, polymorphism could be expressed only with `allOf`, just referring to the base class. Still, some code generators work better without the use of `oneOf` but I think is more aligned with OAS3 how it is …

Add support for polymorphic Areas

---

code/API_definitions/location.yaml

* correction
Proposal to rename path from `/verify` to `/verifications`, to align with guidelines
Fixes [Issue #30](https://github.com/camaraproject/DeviceLocation/issues/30)
_Here is the trial of PR Template_
```
Path name was changed from `/verify` to `/verifications`
```
[Design guidelines 4.1](https://github.com/camaraproject/WorkingGroups/blob/shilpa-padgaonkar-patch-2-1/Commonalities/documentation/API-design-guidelines.md):
```
The URI at the business entity level will always be a plural noun.
```

Update path name

---

code/API_definitions/Get DeviceLocation.yaml

First stab for API definition for **retrieving a device location**. There are points to be commented in this PR and discussed in team meeting:
- I've not yet provided any documentation - will do once we agreed on the interface directly in the OAS.
- Use of device identifiers as defined in latest QoD version (phoneNumber an not MSISDN) - this introduce a gap with the check api.
- Definition of a specific scope distinct from the check operation
- In the response only lat/log & accuracy are provided. I opted to provided straightforward information and not use area schema (with oneOf) --> could be challenged.
- We need some update on the other api - for example the little for the existing api should be check device location API instead of device location API. 
- etc.

Swagger definition for Get device location

---

code/API_definitions/geofencing.yaml

* correction
- Removes the event "org.camaraproject.geofencing.v0.subscription-ends" out of the _/subscriptions_ - request. 
Only use this event for CloudEvent - callbacks.
- Replace single-quotes with double-quotes
Fixes #113

move "org.camaraproject.geofencing.v0.subscription-ends" out of /subscriptions - request

---

code/API_definitions/location-verification.yaml

* correction
* cleanup
- Update documention in info.description with latest atributes included
- Examples updated and enhanced
- Document behaviour when maxAge cannot be satisfied
- Removed required for `lastLocationTime` in response as there may be cases when there is no historical location data for the device
- IPV6 address must identify a single address  
Fixes #102 , #112

location-verification.yaml v0.2 Release Candidate

---

CHANGELOG.md
README.md

* correction
Fix the link to the correct branch for release 0.1.0.
The current path leads to 404.

fix: reference to the correct branch "release-v0.1.0" for release 0.1.0

---

documentation/MeetingMinutes/MoM-2024-01-30.md

Agenda for next meeting. to be updated with minutes

Meeting minutes: MoM-2024-01-30.md

---

code/API_definitions/location-retrieval.yaml

* correction
Very small update. Updating the "RETRIEVAL_POLYGON" example - changed "polygon" to "POLYGON" to align with expected enum String. The RETRIEVAL_POLYGON response example was failing Schema validation in local mock tool ([Prism](https://github.com/stoplightio/prism)).
```
release-note
Updated examples/RETRIEVAL_POLYGON - changed "polygon" to "POLYGON"
```

Minor update - changing "polygon" to "POLYGON" in example to align with enum case

---

code/API_definitions/geofencing.yaml

* bug
Fixes the reference to the component SubscriptionEventType

fix: correct $ref for SubscriptionEventType in geofencing

---

code/API_definitions/location-retrieval.yaml

Update location-retrieval with x-correlator
This PR partially solve Issue #160
(2 other PR come for the 2 other APIs)
Fixes #
/!\ Changed the version to version: 0.2.0-wip
Alignement with CAMARA Guidelines
```
release-note
- add x-correlator as parameter for location-retrieval
```
```
docs
```

Update location-retrieval with x-correlator

---

code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

* correction
Make '+' mandatory for phoneNumber
Fixes #
```
release-note
- Make '+' mandatory for phoneNumber
```
```
docs
```

Make '+' mandatory for phoneNumber - Location Retrieval / Location Verification

---

code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

Fixes #184 
```
release-note
- Remove minimum 60 seconds to maxAge.
-  Absence of maxAge means "any age"
-  maxAge=0 means a fresh calculation.
```
```
docs
```

Adjust maxAge minimum & documentation

---

code/API_definitions/location-retrieval.yaml

* correction
Align the documentation part of the API with the fact that `lastLocationTime` is mandatory in all response.
See line 40
Fixes #197 
```
release-note
```
```
docs
```

Update location-retrieval for lastLocationTime documentation cardinality

---

code/API_definitions/geofencing-subscriptions.yaml

* correction
Update of the subscription-models based on: 
- https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#12-subscription-notification--event
- https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml
- Fixes #124 
- Fixes #118 
- Fixes #200

Update the geofencing subscription models to align on CAMARA commonalities

---

code/API_definitions/geofencing-subscriptions.yaml
code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

Adds the `Authorization and authentication` to the `info.description`
Fixes #212

Add `Authorization and authentication` in `info.description`

---

code/Test_definitions/location-verification.feature
code/Test_definitions/verifyLocation.feature

* tests
Example of testing plan aligned with the guidelines being proposed in https://github.com/camaraproject/Commonalities/issues/158.
Fixes #208 
There are many comments embedded in the test plan to clarify and explain some scenarios. In some cases alternate syntax for the same functionality is used to illustrate the possibilities.
Some points are still open to discussion, such as the degree of specification of the testing plan.

Testing plan for location verification

---

documentation/API_documentation/location-retrieval-API-Readiness-Checklist.md

Add Readiness checklist
Fixes #
PR required to fulfill this checklist: #221 #229
```
release-note
```
```
docs
```

Add Readiness checklist for Location-Retrieval

---

code/location-verification-API-Readiness-Checklist.md
documentation/SupportingDocuments/API-Readiness-Checklist_location-verification-1.0.0.md

Checklist in MetaRelase for location-verification API to become stable (v1.0.0) based on current v0.3.0
Fixes #220

Create Location Verification API readiness checklist

---

code/API_definitions/location-retrieval.yaml

Alignement of errors according to Commonalities guideline.
Fixes #219 
```
release-note
- Aligned error code list & description with Commonalities
```
```
docs
```

location-retrieval: Alignment of errors with Commonalities

---

code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

* correction
Updating the `maxAge`-behaviour for location-verification and location-retrieval
Fixes #216

Update `maxAge`-behaviour for `/verify` & `/retrieve`

---

code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

Adopt Commonalities recommendations regarding usage of device
- device no longer required in request body
- New text in description: https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#appendix-a-infodescription-template-for-device-identification-from-access-token
- Updated/New examples for request bodies without device
Fixes #228
We have to update test plans later with some new scenario
```
device made optional in request body with indications
```

Align device object with Guidelines Issue #228

---

CHANGELOG.md
README.md
code/API_definitions/location-verification.yaml
code/Test_definitions/location-verification.feature

Reverts camaraproject/DeviceLocation#238

Revert "Prepare release 1.1 for location-verification + README + CHANGELOG"

---

CODEOWNERS

Add @maxl2287 as codeowner for Device Location
Fixes #
This PR duplicates https://github.com/camaraproject/DeviceLocation/pull/236 as that one was not merged against main, but against another branch which is no longer valid
```
release-note
```
```
docs
```

Add Max(DT) to CODEOWNERS

---

code/API_definitions/geofencing-subscriptions.yaml

Adds a new termination-reason for "subscription-ends" - CloudEvent, when the user deletes the subscriptions via 
`DELETE /subscriptions/{subscriptionId}`
Fixes #141

geofencing: Add `SUBSCRIPTION_DELETED` as termination-reason

---

code/API_definitions/geofencing-subscriptions.yaml

Alignement of errors according to Commonalities guideline.
Fixes #222 
```
release-note
- Aligned error code list with Commonalities for geofencing API
```

geofencing: Alignment of errors with Commonalities 

---

code/API_definitions/geofencing-subscriptions.yaml

Prepare geofencing-subscriptions for r1.1

Prepare release 1.1 for geofencing-subscriptions

---

code/API_definitions/geofencing-subscriptions.yaml

Adds handling when the provided subscription area cannot be covered or is too small to receive any notifications.
Fixes #198

Add handling when the requested geofence `area` cannot be covered

---

code/Test_definitions/Location-Retrieval.feature
code/Test_definitions/location-verification.feature

* correction
* tests
Corrects feedback from linting
Fixes #253 
Some apply also to location-retrieval.feature

Fix linting complaints

---

code/API_definitions/geofencing-subscriptions.yaml

* correction
Removing this `allOf` aligns with the Commonalities latest version.
It was also discovered that for some code-generators it will produce unexpected behaviors having the `description` inside the `allOf`.
Fixes #264 
```
[geofencing-subscriptions]: remove `allOf` in `sinkCredential`
```

[geofencing-subscriptions]: remove `allOf` in `sinkCredential`

---

code/API_definitions/geofencing-subscriptions.yaml

* correction
Correct the example and some typos.
Fixes #266

Correct the example for sub - initialEvent and error MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED and some typos.

---

code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

* correction
Fixing a typo / mistake in the error for `GENERIC_422_UNSUPPORTED_DEVICE_IDENTIFIERS`
Fixes #260

Update errormessage for unsupported device identifieres

---

code/API_definitions/location-retrieval.yaml

add `maxSurface` management
Fixes #255 
```
release-note
- Add management of maxSurface in request.
```
```
docs
```

Update location-retrieval with add `maxSurface` management

---

code/API_definitions/location-verification.yaml
code/Test_definitions/location-verification.feature

Updates location-verification API with the changes derived from Commonalities and ICM updates
x-camara-guidelines: 0.5.0
Fixes #276, #277 
There are still some open discussions in Commonalities that may impact this PR, so we will keep it open until there is a final version for x-camara-guidelines: 0.5.0
```
* Error schemas updated with enums
* Some error status and codes have been updated
* Section with guidelines about how to identify the device from access token and request body has been updated 
```

Update location-verification.yaml for Spring25

---

code/API_definitions/location-retrieval.yaml
code/Test_definitions/location-retrieval.feature

Updates location-retrieval API with the changes derived from Commonalities and ICM updates
x-camara-guidelines: 0.5.0
Fixes #276, #279 
There are still some open discussions in Commonalities that may impact this PR, so we will keep it open until there is a final version for x-camara-guidelines: 0.5.0
```
* Error schemas updated with enums
* Some error status and codes have been updated
* Section with guidelines about how to identify the device from access token and request body has been updated 
*  Test definitions aligned with API specification update
```
```
docs
```

Update location-retrieval for Spring25

---

code/API_definitions/geofencing-subscriptions.yaml
code/API_definitions/location-verification.yaml
code/Test_definitions/geofencing-subscriptions.feature

This PR decreses the minimum of a circle-area radius to "1".
The provider of the API can restrict then the minimum and respond with HTTP-422 if the size of the area is to small and cannot be covered.
Fixes #282 
```
release-note
* [location-verification / geofencing]: decrease radius minimum to "1" for circle-area
```

[location-verification / geofencing]: decrease radius minimum to "1" for circle-area

---

code/API_definitions/geofencing-subscriptions.yaml
code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

Current documentation omits the potential problem with phone numbers identifying a MultiSIM group. As there is no a single behaviour agreed in CAMARA yet, the proposed enhancement presents the problem and gives some hints to mitigate it
Fixes #257
```
* Adding section for "Multi-SIM scenario handling" in info.description
```

Add MultiSIM section to info.description

---

code/API_definitions/geofencing-subscriptions.yaml

* correction
Fixes #297 
```
release-note
Update geofencing-subscriptions.yaml to make the Device object optional.
```
None

Set Device Object To Optional - According to API Design Guidelines

---

code/API_definitions/geofencing-subscriptions.yaml
code/Test_definitions/geofencing-subscriptions.feature

* correction
Adds the `MISSING_IDENTIFIER` error in the 422 response.
Fixes #300 
```
release-note
* add "MISSING_IDENTIFIER" to the 422 response of geofencing-subscriptions
```

[geofencing-subscriptions]: Add "MISSING_IDENTIFIER" to the 422-error codes

---

code/API_definitions/location-retrieval.yaml

* correction
Remove 400 OUT_OF_RANGE as no UC for it.
Remove 400 LOCATION_RETRIEVAL.MAXAGE_INVALID_ARGUMENT and keep only 422 UNABLE_TO_FULFILL_MAX_AGE
Fixes #315 
```
release-note
- Remove 400 OUT_OF_RANGE as no UC for it.
- Remove 400 LOCATION_RETRIEVAL.MAXAGE_INVALID_ARGUMENT as redundant with 422 UNABLE_TO_FULFILL_MAX_AGE.
```
```
docs
```

Location Retrieval - Remove unnecessary error 400

---

.github/ISSUE_TEMPLATE/config.yml
README.md

Changes the usage of viewing Swagger-UI via editor-next.swagger.io
Fixes #325

Update links in README to use editor-next.swagger.io & update reference to CAMARA API Guideline

---

code/API_definitions/geofencing-subscriptions.yaml

Define `id` to be mandatory in SubscriptionAsync
Fixes #355 
```
release-note
* Define `id` to be mandatory in SubscriptionAsync
```

[geofencing-subscriptions]: Define `id` to be mandatory in SubscriptionAsync

---

code/API_definitions/geofencing-subscriptions.yaml
code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml
code/Test_definitions/geofencing-subscriptions.feature
code/Test_definitions/location-retrieval.feature
code/Test_definitions/location-verification.feature

As of latest Commonalities:
* 422 IDENTIIFIERS_MISMATCH error has been deprecated
* New `DeviceResponse` schema introduced which limits maxProperties: 1,  to be uses in responses (and events) back to the client in cases where multiple identifiers were provided
This PR removes the error and adapts requests and responses to the new Device schemas. Descriptions and some documentation is aligned as well.
Fixes #347 
Some of the changes would be potentially updated as well in the Commonalities artifacts 
```
- Error 422 IDENTIFIERS_MISMATCH deprecated
- Device object in responses is now limited to one identifier (to be chosen by the implementation among the ones provided by the client in cases where several are included in the request)
```

Remove IDENTIFIER_MISMATCH error and associated test cases

---

code/API_definitions/geofencing-subscriptions.yaml
code/API_definitions/location-retrieval.yaml
code/API_definitions/location-verification.yaml

- Updates descriptions of properties of type=string and format=date-time
- Updates descriptions in ErrorModel
Fixes #366 
In ErrorModel I have kept the order that we had (status, code, message) even if in CAMARA_common.yaml is now (message, status, code) because all error responses examples show the previous order.
```
- Align some properties descriptions to latest guidelines
```

Alignment with Commonalities r3.3
