camaraproject/DeviceLocation

- code/API_definitions/location.yaml
Initial contribution of the API spec location.yaml with the version 0.1.0. #4 
The API enables to verify the current position of the UE against given coordinates and accuracy.
> Initial contribution of API spec location.yaml v0.1.0

- code/API_definitions/location.yaml
Reverts camaraproject/DeviceLocation#9
> Revert "Update location.yaml"

- documentation/MeetingMinutes/MoM-2023-01-31.md
- documentation/MeetingMinutes/README.MD
> Draft MoM 2023-01-31

- code/API_definitions/location.yaml
Added `status` property to all errors
> Alignment of errors to guidelines

- code/API_definitions/location.yaml
As discussed in https://github.com/camaraproject/DeviceLocation/issues/20
- New enum value with an optional new property
- Examples and descriptions enhanced
> Cover partial matches in verification result

- README.md
Time zone adjusted to CET/CEST to cover summer time
> Update README.md with summer time zone

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue_correction_template.md
- .github/ISSUE_TEMPLATE/issue_documentation_template.md
- .github/ISSUE_TEMPLATE/issue_enhancement_template.md
- .github/ISSUE_TEMPLATE/issue_pm_template.md
- .github/ISSUE_TEMPLATE/issue_tests_template.md
- .github/pull_request_template.md
Fixes #63
```
Added Github templates for Issues and PRs
```
[Templates How-to](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Issue%20and%20PR%20template%20Howto.md)
> Github templates

- code/API_definitions/location-verification.yaml
* Units to meters
Discussed in Commonalities and meetings
* Keep same limits
* format as integer
```
accuracy units changed to meters
```
> fix/ location-verification: Change-units-to-meters

- code/API_definitions/location-verification.yaml
* correction
* Rename /verifications path to /verify
* Remove some commented lines
Fixes #84
> Location-verification, rename /verifications to /verify

- code/API_definitions/location-retrieval.yaml
Added Documentation + Added precision about use of RFC3339 for the date time.
Added Documentation + Added precision about use of RFC3339 for the date time.
Fixes #40 
```
- added documentation for the API
- precise use of RFC 3339 for the datetime attribute
```
```
docs
```
> Add documentation + update date time attribute description

- documentation/MeetingMinutes/MoM-2023-09-26.md
Agenda for next meeting. It will be updated with minutes after meeting
> Agenda for Meeting 2023-09-26

- code/API_definitions/location-verification.yaml
Aligns security and securityScheme to guidelines in Commonalities and I&CM WG
Identity & Consent Management [Issue #57](https://github.com/camaraproject/IdentityAndConsentManagement/issues/57)
Commonalities [Issue #53](https://github.com/camaraproject/Commonalities/issues/53)
Draft while PR in other groups is not merged 
```
Define OpenIDConnect as security scheme. Adjust scopes.
```
> Update security for location-verification

- documentation/MeetingMinutes/MoM-2023-10-24.md
Agenda to be completed with minutes after meeting
> Meeting 2023-10-24: Agenda and minutes 

- documentation/MeetingMinutes/CAMARA Device Location - 2023-12-05.md
Preparation for Device Location Dec 5th,2023 meeting.
Dec 5th meeting minutes
to be completed with @fernandopradocabrillo 
```
docs
```
> 2023-12-05 Meeting Minutes proposal

- code/API_definitions/location-verification.yaml
* correction
Fix unsupported type/format
Fixes #123
> Fix MaxAge type

- code/API_definitions/location-retrieval.yaml
Prepare PR for location-retrieval release candidate
issue #112 
Prepare release candidate for location-retrieval
Fixes #
Not yet ready for merging --> waiting for ipv6 resolution
```
release-note
- Changed version to v0.1.0-rc
```
```
docs
```
> Update location-retrieval.yaml for release candidate

- code/API_definitions/geofencing.yaml
According to #112 
Prepared release-candidate 0.1.0-rc, including some corrections
```
- Changed version to v0.1.0-rc
```
> Update geofencing.yaml for release candidate 0.1.0-rc

- documentation/MeetingMinutes/MoM-2023-12-05.md
- documentation/MeetingMinutes/MoM-2023-12-19.md
Agenda for next meeting, to be updated with minutes after meeting.
> Agenda for meeting 2023-12-19

- CHANGELOG.md
- README.md
In preparation for Release 0.2:
- README updated
- New CHANGELOG with changes from 0.1 to 0.2
Links pointing to release-0.2.0 branch will not work until the branch is created with this PR is merged.
#112
> Doc/release notes 0.2

- code/API_definitions/geofencing.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
* correction
Fix desalignment regarding areaType values
Fixes #131 
To be incorporated to RC
```
* areaType is now an enum in UPPER_CASE for all 3 APIs
```
> AreaType as enum

- CHANGELOG.md
- README.md
Adjust README and CHANGELOG for upcoming release-0.2.0-rc2
> Prepare RC2

- code/API_definitions/geofencing.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
* bug
* correction
(all) Correct YAML examples to use upper case enum of areaType
(geofencing) Rename in the OAS SubscriptionEventType to NotificationEventType
(retrieval) Fix format for attribute lastLocationTime in location retrieval 
(retrieval & verification) Revise Description to Meet GDPR Compliance - REMOVAL OF " Location-based advertising" in Documentation (sentence from @iamdatanick  proposal)
Fixes #136 
Fixes #139 
Fixes #137 
Fixes #135 
```
Correct YAML examples to use upper case enum of areaType
-For geofencing: Rename in the OAS SubscriptionEventType to NotificationEventType
-For Retrieval:  Fix format for attribute lastLocationTime in location retrieval 
Revise Description to Meet GDPR Compliance - REMOVAL OF " Location-based advertising" in …
```
> Global fixes for minor updates & corrections

- code/API_definitions/location-verification.yaml
* correction
Fixes wrong example
Fixes #145
> location-verification: Fix Area example 

- code/API_definitions/location-retrieval.yaml
* correction
Fix example from polygon to POLYGON
Fixes #147 
It's a fix over rc2 which has been just released, as it only affects an example
> Fix example from polygon to POLYGON

- README.md
- code/API_definitions/geofencing.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
* correction
- Some fixes detected by linting:
- Add tags section
- Add some descriptions to operations
- Fix example in Geofencing (id is string)
- Change links in README to rc3
> Prepare Release 0.2.0 rc3

- documentation/MeetingMinutes/MoM-2024-02-13.md
Agenda for next meeting, to be updated with minutes
> Meeting 2024-02-13

- README.md
- documentation/MeetingMinutes/MoM-2024-02-13.md
* correction
Some fixes detected after the branch was created
> Sync 0.2.0-rc3 branch with main

- documentation/MeetingMinutes/MoM-2024-02-27.md
Agenda for next meeting to be updated with minutes.
> MoM-2024-02-27.md

- CHANGELOG.md
- README.md
- code/API_definitions/geofencing.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
* Branch for Release v0.2.0
* Updated links
Once review and merged the corresponding release and tag will be created
> Release v0.2.0

- documentation/MeetingMinutes/MoM-2024-03-12.md
Agenda for next meeting, to be updated with minutes after meeting
> MoM-2024-03-12.md

- code/API_definitions/location-verification.yaml
Update location-verification with x-correlator
This PR partially solve Issue https://github.com/camaraproject/DeviceLocation/issues/160
(2 other PR will come for the 2 other APIs)
Fixes #
Alignement with CAMARA Guidelines
```
release-note
- add x-correlator as parameter for location-verification
```
```
docs
```
> Update location-verification with x-correlator

- code/API_definitions/geofencing.yaml
Update location-verification with x-correlator
This PR partially solve Issue #160
(2 other PR are done for the 2 other APIs)
Update location-verification with x-correlator
This PR partially solve Issue #160
(2 other PR are done for the 2 other APIs)
Fixes #
Discussion in https://github.com/camaraproject/Commonalities/issues/164 to solve question about x-correlator in notification.
```
release-note
- add x-correlator as parameter for geofencing
```
```
docs
```
> Update geofencing.yaml with x-correlator

- code/API_definitions/geofencing.yaml
* correction
Make '+' mandatory for phoneNumber
(complete #177)
Fixes #177 
```
release-note
Make '+' mandatory for phoneNumber
```
```
docs
```
> Make '+' mandatory for phoneNumber

- CODEOWNERS
- MAINTAINERS.MD
> 203 update and review codeowners and maintainersmd file

- README.md
* correction
README still had previous Teams link
> Update meeting link

- code/API_definitions/location-verification.yaml
- Errors according to new Commonalities guidelines
- Now all errors tested in test plan are explicitly indicated in the spec
- Added some descriptions to make linter happy
Fixes #214
> location-verification: Alignment of errors with Commonalities

- CODEOWNERS
add @maxl2287 as codeowner for Device Location
Fixes #
```
release-note
```
```
docs
```
> Add Max as codeowner

- CHANGELOG.md
- README.md
- code/API_definitions/location-verification.yaml
- code/Test_definitions/location-verification.feature
* correction
Prepare location-verification for r1.1
Some fixes after review
Update README (for the 3 APIs)
Update CHANGELOG (for location-verification + placeholders for the others)
> Prepare release 1.1 for location-verification + README + CHANGELOG

- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
* correction
* cleanup
Aligns both APIs between them
Adds note about networkAccessIdentifier not to be used with this version of guidelines
contact info not to be included
license info to be included
Fixes #
```
release-note
```
```
docs
```
> Latest alignments and fixes for verification and retrieval

- code/API_definitions/geofencing-subscriptions.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
* correction
Align specs with review guidelines
> Update externalDocs for rc.1

- README.md
Adding the (missing) badge "Latest Release" from https://github.com/camaraproject/Template_API_Repository
Fixes # na / minor fix
> Update README.md - adding badge "Latest Release" 

- README.md
Set new meeting schedule, fixed to UTC
Fixes #273
> Update meeting time in README.md 

- code/Test_definitions/geofencing-subscriptions.feature
* tests
This PR adds additional test-defintions for HTTP-422 error-cases.
Fixes #288 
```
release-note
* Add test-definitions for HTTP-422 error-cases for geofencing-API
```
> Add test-definitions for HTTP-422 error-cases for geofencing-API

- code/API_definitions/geofencing-subscriptions.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
- code/Test_definitions/geofencing-subscriptions.feature
- code/Test_definitions/location-retrieval.feature
- code/Test_definitions/location-verification.feature
Reset version numbers to wip following publication of release candidate
> Reset version numbers to wip following r2.1

- code/API_definitions/location-verification.yaml
Enhance description to clarify usage after discussion in #308 
Partially resolves #308 for this meta
Issue to keep open
> Enhance description UNKNOWN vs UNABLE_TO_FULFILL_MAX_AGE

- code/API_definitions/location-retrieval.yaml
- code/Test_definitions/location-retrieval.feature
* correction
- Remove 429 from the yaml
- add a summary for all examples in the yaml
- add a 403 Test Case in the feature file
- shift to 422 the Test Case for Missing Identifier 
Fixes #307 
404 NOT_FOUND is exceptionally kept in the spec even if there is no test for it
```
release-note
```
```
docs
```
> Location Retrieval - Align Error Test

- code/API_definitions/geofencing-subscriptions.yaml
* correction
Aligns on Commonalities r2.3
Fixes #302
```
release-note
* [geofencing-subscriptions]: Alignment on commonalities r2.3
```
> [geofencing-subscriptions]: Alignment on commonalities r2.3

- MAINTAINERS.MD
Update Vodafone contact in MAINTAINERS.MD
Fixes # N/A
None
```
release-note
- Update Vodafone contact in MAINTAINERS.MD
```
None
> Update Vodafone contact in MAINTAINERS.MD

- code/API_definitions/geofencing-subscriptions.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
- code/Test_definitions/geofencing-subscriptions.feature
- code/Test_definitions/location-retrieval.feature
- code/Test_definitions/location-verification.feature
Back to `wip` for the version of the yaml
Fixes #319 
```
release-note
```
```
docs
```
> Back to wip

- code/API_definitions/geofencing-subscriptions.yaml
* correction
Remove AUTHENTICATION_REQUIRED error code
Fixes #339 
This error code was not described in a scenario in the .feature file.
This is a **breaking** change.
```
release-note
- Remove AUTHENTICATION_REQUIRED error code
```
```
docs
```
> remove AUTHENTICATION_REQUIRED in  geofencing-subscriptions.yaml

- code/API_definitions/geofencing-subscriptions.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
- code/Test_definitions/geofencing-subscriptions.feature
- code/Test_definitions/location-retrieval.feature
- code/Test_definitions/location-verification.feature
* correction
Update x-correlator format
Fixes #342 
Not a breaking change
```
release-note
- Update x-correlator format
```
```
docs
```
> Update x-correlator format

- code/API_definitions/geofencing-subscriptions.yaml
* correction
Missing security scheme for notificationsBearerAuth
Fixes #362
> Missing security scheme notificationsBearerAuth in geo-fencing-subscription

- CHANGELOG.md
- README.md
- code/API_definitions/geofencing-subscriptions.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
- code/Test_definitions/geofencing-subscriptions.feature
- code/Test_definitions/location-retrieval.feature
- code/Test_definitions/location-verification.feature
- documentation/API_documentation/geofencing-subscriptions-API-Readiness-Checklist.md
- documentation/API_documentation/location-retrieval-API-Readiness-Checklist.md
- documentation/API_documentation/location-verification-API-Readiness-Checklist.md
Adjustments needed before the creation of pre-release r3.1
Fixes #350 
We need to merge first all other PRs with scope intended to be part of this first RC.1
> Prepare r3.1

- code/API_definitions/geofencing-subscriptions.yaml
- code/API_definitions/location-retrieval.yaml
- code/API_definitions/location-verification.yaml
- code/Test_definitions/geofencing-subscriptions.feature
- code/Test_definitions/location-retrieval.feature
- code/Test_definitions/location-verification.feature
Repo maintenance after release creation 
n/a
> Reset versions in OAS and test plans to WIP
